objective_params:
  feature_fraction:
    max: 1.0
    min: 0.1
  learning_rate:
    log: true
    max: 0.1
    min: 0.0001
  max_depth:
    max: 10
    min: 3
  num_leaves:
    max: 50
    min: 10
  num_trees:
    log: false
    max: 100
    min: 10
objective_values: mean
